name: Publish wiki
on:
  push:
    branches: [main]
    paths:
      - docs/**
      - .github/workflows/publish-wiki.yml
  workflow_dispatch:
permissions:
  contents: write
jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: build wiki
        run: |
          pip install -e .
          pip install -r docs/docs_source/requirements.txt
          make -C docs/docs_source markdown
      - name: move markdown pages
        run: |
          mkdir -p docs/API
          rm docs/docs_source/build/markdown/index.md
          mv docs/docs_source/build/markdown/* docs/API/
          # remove source_dir
          rm -r docs/docs_source
      - uses: Andrew-Chen-Wang/github-wiki-action@v4
        with:
          path: docs/